### ISSUE TITLE
Filter Products by MPN

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/docs#126]
As discussed in this [slack thread](https://bigcommerce-devs.slack.com/archives/C012R9319AT/p1708642318060049?thread_ts=1708640166.618919&cid=C012R9319AT) (BigCommerce Devs slack), it is possible to filter `v3/catalog/products` endpoint via `?mpn={foo}`, however, it is undocumented currently. 

PR incoming...

**Comment by harnerdesigns** [comment]
Beat me to it! 🤘🏽

**Comment by bc-traciporter** [comment]
I just merged the PR for this issue, therefore closing this Issue.
