### ISSUE TITLE
Orders V2 Create/Update does not accept values for tax_provider_id

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/docs#144]
As highlighted on [BigCommerceDevs Slack](https://bigcommerce-devs.slack.com/archives/C012R9319AT/p1709311427053969), and confirmed by @bc-hnbarr on [forum here](https://support.bigcommerce.com/s/question/0D54O00007FNy8uSAD/tax-provider-id-via-order-api-post?language=en_US), OrdersV2 Create/Update does not accept a value for `tax_provider_id`.

The value should be shown as 'Read Only', and the enum reference removed to show that the value is not adhered to. 

(Although - strangely, supplying this does not cause the request to error, it is simply ignored.)

**Comment by bc-tgomez** [comment]
Thanks @AndrewBarber for the catch and PR! 🙇  I'll get on this one.

**Comment by bc-tgomez** [comment]
Your contribution should be live on our site shortly.

**Comment by AndrewBarber** [comment]
Nice 👌 
I don't think I can self-close the issue. If you can that would be great! 👍

**Comment by AndrewBarber** [comment]
Oh - I can! Cheers!
