### ISSUE TITLE
Feedback for “Blog Posts”

### ISSUE THREAD

**Issue by edpol** [bigcommerce/docs#150]
Was able to download the first 50 of 113 blogs.  Need to have one example that shows how to get the rest.

**Comment by bc-andreadao** [comment]
@edpol Thanks for the feedback. We can look into how to update the docs for this.

**Comment by bc-andreadao** [comment]
@edpol There is an example in the GraphQL docs that can help you [paginate your responses](https://developer.bigcommerce.com/docs/storefront/graphql#pagination)
