### ISSUE TITLE
Stencil CLI Node Version 20.10 not supported (yet?)

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/docs#17]
### Issue
The [stencil-cli install documentation](https://developer.bigcommerce.com/docs/storefront/stencil/cli/install) advises to use node version `20.10.0`, however, most @bigcommerce libraries do not support v20. Instead looking for node versions lower than 19 and higher than 16.

Using node v20 results in the following errors when using Cornerstone.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bigcommerce/stencil-cli@7.3.1',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <19.0.0', npm: '>=8.0.0 <10.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bigcommerce/stencil-styles@5.2.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bigcommerce/stencil-utils@6.15.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
```

The PR seems to be [here](https://github.com/bigcommerce/docs/pull/14).

### Resolution

The PR should be reverted to advise to use node v18.15.

**Comment by bc-traciporter** [comment]
Thank you @AndrewBarber . I created [PR 27](https://github.com/bigcommerce/docs/pull/27) to change the node version back.

**Comment by slsriehl** [comment]
#27 is merged!
