### ISSUE TITLE
Feedback for “Store Logs”

### ISSUE THREAD

**Issue by pgorizo** [bigcommerce/docs#170]
https://api.bigcommerce.com/stores/store_hash/v3/store/systemlogs?date_created:max=1749373600
1749373600 = March 12, 2024, 00:00:00 (UTC)
Should return results and the last dated log was dated for 2023-01-25T15:51:39+00:00 we have made modifications that should have logged past this date. 

I also cant add another parameter such as ?date_created:min=1749373600&date_created:max=1710395999. It provides a 200 response but data was returned and there is logs for this date range.

**Comment by bc-traciporter** [comment]
Hello @pgorizo Thank you for your feedback. We are working with the development team to resolve this issue.

**Comment by bc-traciporter** [comment]
@pgorizo Sorry for the delayed response. I learned from the development team that `date_created` is not supported for Store logs. I am in the process of removing it from the Store Logs documentation.
