### ISSUE TITLE
Order Product API does not return order_product_id

### ISSUE THREAD

**Issue by lisastriker** [bigcommerce/docs#173]
When i run a get request https://api.bigcommerce.com/stores/{store}/v2/orders/{order_number}/products. No order_product_id is found

This is my json result
`[
    {
        "id": 108,
        "order_id": 196,
        "product_id": 8250,
        "variant_id": 8215,
        "order_pickup_method_id": 0,
        "order_address_id": 97,
        "name": "Antenna, 3dBi Wifi emONE",
        "name_customer": "Antenna, 3dBi Wifi emONE",
        "name_merchant": "Antenna, 3dBi Wifi emONE",
        "sku": "ANT-008",
        "upc": "",
        "type": "physical",
        "base_price": "25.0000",
        "price_ex_tax": "25.0000",
        "price_inc_tax": "25.0000",
        "price_tax": "0.0000",
        "base_total": "1000.0000",
        "total_ex_tax": "1000.0000",
        "total_inc_tax": "1000.0000",
        "total_tax": "0.0000",
        "weight": "0.0800",
        "width": "0.0000",
        "height": "0.0000",
        "depth": "0.0000",
        "quantity": 40,
        "base_cost_price": "0.0000",
        "cost_price_inc_tax": "0.0000",
        "cost_price_ex_tax": "0.0000",
        "cost_price_tax": "0.0000",
        "is_refunded": false,
        "quantity_refunded": 0,
        "refund_amount": "0.0000",
        "return_id": 0,
        "wrapping_id": 0,
        "wrapping_name": "",
        "base_wrapping_cost": "0.0000",
        "wrapping_cost_ex_tax": "0.0000",
        "wrapping_cost_inc_tax": "0.0000",
        "wrapping_cost_tax": "0.0000",
        "wrapping_message": "",
        "quantity_shipped": 0,
        "event_name": null,
        "event_date": "",
        "fixed_shipping_cost": "0.0000",
        "ebay_item_id": "",
        "ebay_transaction_id": "",
        "option_set_id": null,
        "parent_order_product_id": null,
        "is_bundled_product": false,
        "bin_picking_number": "",
        "external_id": null,
        "fulfillment_source": "",
        "brand": "",
        "gift_certificate_id": null,
        "applied_discounts": [],
        "product_options": [],
        "configurable_fields": [],
        "discounted_total_inc_tax": "1000.0000"
    }
]`

As you can see, there is no order_product_id. This means for this API endpoint https://api.bigcommerce.com/stores/{sttore_id}/v2/orders/{orderr_id}/shipments, i can't create a shipment, because i simply don't have the order_product_id and i have no way to get it.

I'm wondering if this is because of the variant ID. I have a feeling, the variant and product id might have to be combined? I'm not sure what's the problem.
https://api.bigcommerce.com/stores/{store_id}/v2/orders/{order_id}/products/{product_id}
-> This also strangely gives an error once i plug in the product id
![image](https://github.com/bigcommerce/docs/assets/18165904/c73c0d1d-3158-4846-b148-3d683d1cad82)

**Comment by bc-tgomez** [comment]
Hi @lisastriker 👋 After reviewing the response It appears that your `order_product_id` is the first line in the response; `108`. Looking at our documentation I see where that detail could be missed. To correct the confusion for other devs, I'll go ahead and add a supporting note to the `id` description that includes its function when creating shipments. Please let me know if this doesn't solve the issue.

**Comment by bc-tgomez** [comment]
The changes have been made to our documentation. Thank you for your feedback!
