### ISSUE TITLE
Cost Price Value Issue

### ISSUE THREAD

**Issue by Pranay-Kumar-16** [bigcommerce/docs#196]
Hi Team,

I wanted to bring to your attention an observation I made while working on the create variants API. Specifically, I noticed that when the cost_price field is sent as null via API, it defaults to 0. However, when I create a variant from the UI, the cost_price is set to null when fetching the product from the API.

I assume there might be an inconsistency in how the cost_price field is handled between the API and the UI as the API documentation says that the null values and number is accepted.

Could we please review this observation and let me know if it is the expected behavior?

Thank you.

**Comment by bc-traciporter** [comment]
Hi @Pranay-Kumar-16 I assume you are discussing the [Create a Product Variant ](https://developer.bigcommerce.com/docs/rest-catalog/product-variants#create-a-product-variant) endpoint. I will ask the development about the expected behavior.

**Comment by Pranay-Kumar-16** [comment]
Hi @bc-traciporter,

You are right. When I check the documentation for the create-a-product-variant endpoint. It shows as null and zero both are accepted for cost price field but when I create a variant using the endpoint with cost_price= null then it defaults the cost price value to zero.

I hope this helps

thank you

**Comment by bc-traciporter** [comment]
@Pranay-Kumar-16 I received the following information from the developer:
When a NULL value is submitted it will default it into the DB as a 0 ( there will never be a NULL or empty value in DB)
Frontend wise (i.e. Control Panel) all the 0s are treated as Null and it will be displayed as empty.

I will add more clarification in the documentation. Thank you for raising this issue.

**Comment by bc-traciporter** [comment]
Thank you @Pranay-Kumar-16 , the scenarios you described above sound good.

**Comment by Pranay-Kumar-16** [comment]
Can I get more update on the below scenario:
If a variant is created from bigcommerce UI/control panel with cost price as blank then it is saved as null in the database(I confirmed it using the get variant API call). even in this case it is coming from database then why isn't it deafulted to 0. I'm asking this question because it is causing an issue with the inheritance of the parent product prices when created from API.

**Comment by bc-traciporter** [comment]
Hi @Pranay-Kumar-16 Thank you for your patience. Sorry I did not understand your earlier statement.  I went back to the developer and you are correct. Null values have been found in the database. So it is possible to store a null value in the table. Sorry for the confusion.
