### ISSUE TITLE
Feedback for “Schemas”

### ISSUE THREAD

**Issue by electricenjindevops** [bigcommerce/docs#202]
On the schemas documentation we are unable to click the arrows to see more info for array / object structures.

examples:
- facet
- meta
- selected

https://developer.bigcommerce.com/docs/storefront/stencil/themes/context/object-reference/schemas#category

I am using Chrome (latest version) on Windows 10.

**Comment by slsriehl** [comment]
Hi @electricenjindevops -- thanks for developing with BC and opening this issue. This work is ticketed and planned, and I'm going to leave this issue open until it's resolved.

**Comment by electricenjindevops** [comment]
Thanks Sarah, much appreciated! This may or may not be related, but we were
also unable to see meta description in the Category object schema on a
Stencil theme template recently. This is what caused us to view the docs in
the first place - we'll review this again soon, but wondering if maybe the
two issues are related potentially.

**Comment by slsriehl** [comment]
@electricenjindevops There actually isn't any more detail in the schema as we have it now, so this isn't a problem with the docs per se (although they are part of the solution!). I did make a small adjustment to the source file, which you can see in the merged PR above, but it doesn't yet add any of the detail you're after.

We'll make sure there's an open ticket for the engineering group that manages Stencil to check out the issue with meta, as well as a docs ticket to add more detail.

**Comment by bc-traciporter** [comment]
@electricenjindevops I will close this issue due to inactivity. I did confirm that there isn't any more detail in the schemas. Unfortunately the empty arrays are confusing. We have informed our team.
