### ISSUE TITLE
The OpenAPI spec for Customers V3 has a "spelling" error

### ISSUE THREAD

**Issue by gillih** [bigcommerce/docs#212]
The line 1579 in Customers V3 Open API reference spec is

`stored_paypal_account: '#/components/schemas/PaypalAccountInstrument'`

but should be

`stored_paypal_account: '#/components/schemas/PayPalAccountInstrument'`

"Pal" in "PayPal" has the incorrect case

**Comment by TomA-R** [comment]
Thank you for the report! I've opened a PR to fix this
