### ISSUE TITLE
Feedback for “Orders”

### ISSUE THREAD

**Issue by realtebo** [bigcommerce/docs#226]
It's undocumented how to search orders by meta field

for example, we need to find ALL and ONLY orders with this key

    "key": "date_created_woocommerce",

**Comment by realtebo** [comment]
> Hello @realtebo 
> I see in the [Get Order Metafields](https://developer.bigcommerce.com/docs/rest-management/transactions/metafields#get-order-metafields) endpoint, there is a key query parameter. So you can filter based on a metafield's key. Will this endpoint help you?

Sorry but this filters metafileds of a single order.

What we Need is to filter orders based on a metafiled value

**Comment by bc-traciporter** [comment]
Hello @realtebo Sorry for the delay. I reached out to the development team and they said this functionality is not yet available.
