### ISSUE TITLE
Bug in documentation for “Embedded Checkout”

### ISSUE THREAD

**Issue by Tigatok** [bigcommerce/docs#23]
In the "Creating Channel" section, it says this:

Creating a channel
To allow an external website to serve the BigCommerce checkout, create a new channel by sending a POST request to the /channels endpoint.

POST https://api.bigcommerce.com/stores/{{store_hash}}/v3/channels

Create a Channel POST request

{
    "type": "storefront",
    "platform": "custom",
    "name": "https://{your-site}.com"
}

The response will contain an id which we will use as the channel_id in future requests.

That post does not work. It appears that name cannot contain those items. See from postman:

<img width="1103" alt="image" src="https://github.com/bigcommerce/docs/assets/3906461/aea5bf51-503b-41d8-aaa1-9f464073d850">

**Comment by slsriehl** [comment]
You are right. I'll look into changing this.

**Comment by slsriehl** [comment]
This has been updated. Thanks @Tigatok!
