### ISSUE TITLE
Breadcrumbs display error

### ISSUE THREAD

**Issue by theromulans** [bigcommerce/docs#253]
Hi there, there's a bunch or breadcrumb navigation that is appearing incorrectly.

<img width="531" alt="Screenshot 2024-05-06 at 9 37 28 am" src="https://github.com/bigcommerce/docs/assets/10804073/347c5edb-fee4-46a3-9f01-56c6e5ff3400">

Shipping Provider API:

https://developer.bigcommerce.com/docs/rest-contracts/shipping

Others observed:

https://developer.bigcommerce.com/docs/rest-contracts/tax
https://developer.bigcommerce.com/docs/rest-contracts/tax-app-connection

**Comment by bc-andreadao** [comment]
Thanks @theromulans , I've created a ticket for the DevX team
