### ISSUE TITLE
Reset password mutation is not working giving internal server error.

### ISSUE THREAD

**Issue by MJAN123** [bigcommerce/docs#258]
Hi I am trying to implement reset password functionality to my store.
https://developer.bigcommerce.com/docs/storefront/graphql/customers#request-a-password-reset

**Comment by slsriehl** [comment]
Hi @MJAN123 -- thanks for opening this issue. I am looking into it.

**Comment by slsriehl** [comment]
@MJAN123 we have a known issue with a ticket open about this mutation returning an error when a valid replacement password is supplied. Is that what you're running into?

**Comment by slsriehl** [comment]
@MJAN123 The reset password mutation should be working now. Please open a new issue if you have further issues with it or anything else.

Thanks for building with BigCommerce!
