### ISSUE TITLE
Feedback for “Adjustments”

### ISSUE THREAD

**Issue by bc-seamusduffy** [bigcommerce/docs#263]
An absolute adjustment is required before any relative adjustments can be made. This error occurs when a product or a location is created and the `available_inventory` value is null/undefined but displayed as `0` due to the element being an `integer`. 

This should be called out within the dev docs to ensure when a user is building their own inventory mgmt tool they have put in place a system to establish a starting inventory point (whether that's setting to a true 0 or another value).

**Comment by slsriehl** [comment]
Thanks for the feedback, @bc-seamusduffy. I'll make a ticket and we can follow up internally.

**Comment by slsriehl** [comment]
Okay, see [DEVDOCS-5934].
