### ISSUE TITLE
Feedback for “Staying Current with Platform Changes”

### ISSUE THREAD

**Issue by MadisonTillery** [bigcommerce/docs#268]
Should we change verbiage for "changelog/changelogs" to "release notes" as the actual page links to release notes

https://developer.bigcommerce.com/archive/start/partner/staying-current > references _Developer Changelog_ and _changelog_ 

- It actually links to here: https://developer.bigcommerce.com/release-notes 

https://developer.bigcommerce.com/docs/start/about/support#changelog > definition of changelog, could be potentially edited to advise of the change in verbiage only?

**Comment by slsriehl** [comment]
will update when the site rebuilds. Thanks!
