### ISSUE TITLE
Duplicate parameters in some OpenAPI operations

### ISSUE THREAD

**Issue by smcc-riccardoc** [bigcommerce/docs#274]
Hello, while parsing OpenAPI definition files in [docs/reference](https://github.com/bigcommerce/docs/tree/main/reference) using [openapi-typescript](https://openapi-ts.pages.dev/) I have noticed that some operations contain duplicated parameters.

Specifically:
operationId | schema file | duplicated parameters
--- | --- | ---
`getCustomerStoredInstruments` | [customers.v3.yml](https://github.com/bigcommerce/docs/blob/8739e57a8c940b868822203350eb53738dfa72ef/reference/customers.v3.yml#L1596) | `customerId`
`getOrderConsignments` | [orders.v2.oas2.yml](https://github.com/bigcommerce/docs/blob/8739e57a8c940b868822203350eb53738dfa72ef/reference/orders.v2.oas2.yml#L979) | `order_id`
`getThemeConfiguration` | [themes.v3.yml](https://github.com/bigcommerce/docs/blob/8739e57a8c940b868822203350eb53738dfa72ef/reference/themes.v3.yml#L488) | `page`, `limit`
`previewWidget` | [widgets.v3.yml](https://github.com/bigcommerce/docs/blob/8739e57a8c940b868822203350eb53738dfa72ef/reference/widgets.v3.yml#L149) | `uuid`

Also, these duplications appears in the docs at developer.bigcommerce.com, which may cause confusion. Example for the `getCustomerStoredInstruments` operation:
![Duplicated `customerId` parameter in the `getCustomerStoredInstruments` operation](https://github.com/bigcommerce/docs/assets/147587711/fbf83395-fc2f-42ef-ae94-601aacb72d8e)

Is there a reason that I am missing for these duplications to be present?

I am available to open a pull request if there is something that should be fixed.

**Comment by slsriehl** [comment]
@smcc-riccardoc We'll take you up on the PR. This is for sure an error. FYI @bigcommerce/dev-docs 

Thanks for building with BigCommerce. We appreciate you!

**Comment by slsriehl** [comment]
PR is merged. The changes will show up on the site when it rebuilds. Thanks again, @smcc-riccardoc! We appreciate your contribution.
