### ISSUE TITLE
Example JSON for “Batch Metafields”

### ISSUE THREAD

**Issue by atensoftware** [bigcommerce/docs#280]
https://developer.bigcommerce.com/docs/rest-catalog/product-variants/batch-metafields#get-all-product-variant-metafields

Currently, the example JSON is missing **resource_id** and **owner_client_id** in the 200 response body 'data' section.
Instead, add those to the example JSON response.  Especially 'resource_id', since without that, there is no way to link the meta-field value back to its resource.

**Comment by slsriehl** [comment]
Hey @atensoftware -- See the mentioned PR #282 for changes that fix this example to include all the response body properties. They will be live next time the site rebuilds.

Thanks for opening this issue and building with BigCommerce!
