### ISSUE TITLE
Feedback for “Products”

### ISSUE THREAD

**Issue by KmcEA** [bigcommerce/docs#294]
How do i save or update if i want more than related products in our record there old products have 150 plus related products when we are trying to update it does not want us to update the products cause it is too many related

**Comment by bc-traciporter** [comment]
@kristinapototska can you help @KmcEA ?

**Comment by bc-traciporter** [comment]
Hello @KmcEA Are you still needing assistance? If so, you can [submit a support case](https://support.bigcommerce.com/s/article/Creating-Viewing-Support-Cases) to get help saving/updating your related products.
