### ISSUE TITLE
Feedback for “Creating an External Installation Button”

### ISSUE THREAD

**Issue by preetham9498** [bigcommerce/docs#297]
I am unable to test this with my draft app. It says that "This app is not available for installation"

![image](https://github.com/bigcommerce/docs/assets/85742748/8b5f9186-d41e-4a71-b667-4a1038f7b9d9)

Is there any way to test this flow by generating a temporary custom install link for my draft app?

**Comment by bc-traciporter** [comment]
Hello @preetham9498 ,
Thank you for submitting your issue. There is no way to test your flow using a temporary install link. Your draft app must be listed as an app. See the following articles for more information:

- [App Store Approval Requirements](https://developer.bigcommerce.com/docs/integrations/apps/guide/requirements)
- [Creating an External Installation Button](https://developer.bigcommerce.com/docs/integrations/apps/guide/buttons)
