### ISSUE TITLE
Inaccuracy in documentation for embedded checkout

### ISSUE THREAD

**Issue by Tigatok** [bigcommerce/docs#30]
Under [creating a Channel](https://developer.bigcommerce.com/docs/storefront/cart-checkout/embedded-checkout/tutorial#creating-a-channel), it is mentioned that 
>Channels created by API are visible in the store control panel in Products > Listed On. The Orders section also includes a channel filter.

However, I cannot seem to find where that is. Screenshot shows the Product menu, with no "Listed On" spot: 
<img width="255" alt="image" src="https://github.com/bigcommerce/docs/assets/3906461/251b795f-1b85-41be-9d14-3ef4ae64115f">

I _think_ you can view the channels when you go to the channels manager, listed here: *.mybigcommerce.com/manage/channel-manager

**Comment by slsriehl** [comment]
Thanks for bringing this up, @Tigatok. I believe the intent of this sentence is confused, so I'll look into providing something clearer.

**Comment by slsriehl** [comment]
Here's the edit:

<img width="650" alt="Screenshot 2024-01-10 at 13 04 58" src="https://github.com/bigcommerce/docs/assets/15839167/e17bfe3c-3566-4c19-ab8d-7545a14eac67">
