### ISSUE TITLE
Feedback for “Webhook Events”, Get Events

### ISSUE THREAD

**Issue by cjbarth** [bigcommerce/docs#300]
https://developer.bigcommerce.com/docs/webhooks/webhooks/webhook-events#get-events is listed as deprecated, but there is no note about what the replacement or alternative is.

**Comment by bc-traciporter** [comment]
Hello @cjbarth I don't think there is a replacement. But, I will reach out to the development team and try to find out more information.

**Comment by bc-traciporter** [comment]
Hi @cjbarth I learned this endpoint should have never been posted to our public docs. Also, this endpoint never worked as expected, and the feature to utilize it was never fully implemented, so there is no need to replace it.

**Comment by cjbarth** [comment]
In that case, you can't just mark it `deprecated`. That API looks very useful for something I want to do, but if it is broken, never worked, and shouldn't be used, it should have a little stronger warning on it. It should probably have its return adjusted to always return a 5xx error.

**Comment by bc-traciporter** [comment]
@cjbarth sorry, I didn't read your message closely. I will work with the development team to determine the best way to address this issue.

**Comment by bc-traciporter** [comment]
Hello @cjbarth I created a PR to add in the replacement for this endpoint. 
See [PR 309](https://github.com/bigcommerce/docs/pull/309/files).
