### ISSUE TITLE
Migrate open issues from api-specs

### ISSUE THREAD

**Issue by Charlieface** [bigcommerce/docs#31]
All open issues from the old archived repo bigcommerce/api-specs should be migrated.

it would be helpful if they were actually responded to as well, because most of them have been open for some time with no response.

**Comment by slsriehl** [comment]
@Charlieface absolutely. We are in the process of addressing the old open issues from bigcommerce/api-specs and bigcommerce/dev-docs so we can fully archive those repos.

I'll leave this issue open until we're done. :)

Thanks for opening this. We appreciate your contribution to our DX.

**Comment by slsriehl** [comment]
The bigcommerce/api-specs issues are addressed and closed. I'm going to continue to keep this open until bigcommerce/dev-docs is migrated and we're fully moved in to this repo.

**Comment by bc-traciporter** [comment]
Closing this issue as bigcommerce/dev-docs has been migrated over.
