### ISSUE TITLE
Feedback for “Installing Stencil CLI”

### ISSUE THREAD

**Issue by bobghkuranda** [bigcommerce/docs#33]
Following this guide at the time of writing install gives a couple unsupported versions warnings on MacOS Sonoma

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bigcommerce/stencil-cli@7.3.1',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <19.0.0', npm: '>=8.0.0 <10.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bigcommerce/stencil-styles@5.2.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

Running stencil bundle then conflicts with the Node version the instructions listed to install

Error: You are running an unsupported version of node. Please upgrade to >=16.0.0 <19.0.0

**Comment by slsriehl** [comment]
Hi @bobghkuranda! Thanks for raising this issue and building with BigCommerce. We published this change a bit early -- the document has been updated to reflect Node 18 as the recommended version. See #27.
