### ISSUE TITLE
Missing product param googleproductsearch

### ISSUE THREAD

**Issue by IlyaZha** [bigcommerce/docs#350]
### What is the link to the page that needs updating? Provide multiple links if needed.

https://developer.bigcommerce.com/docs/rest-catalog/products

### What needs to be documented?

API users can get google product search param through an endpoint `endpoint /products/${productId}/googleproductsearch`. It isn't documented now.

### What is currently documented?

Now documented to receive product parameters: Complex rules, Custom fields, Images, Metafields, Reviews, Videos

**Comment by IlyaZha** [comment]
Additional question: is it possible to get `googleproductsearch` not from one product, but for all products?

**Comment by bc-traciporter** [comment]
Hello @IlyaZha 
Sorry for the delayed in response. `googleproductsearch` is a very old endpoint; we removed this field from our documentation. However, it is still present in our database. Thank you for asking us about it. The development team is now in the process of removing it and cleaning up this change.

**Comment by IlyaZha** [comment]
@bc-traciporter Hello! We use this endpoint in our application. Do you have a replacement for it? 
How to get googleproductsearch information when you remove this endpoint?
Please, don't remove it if there is no another way to get googleproductsearch information!

**Comment by IlyaZha** [comment]
@bc-traciporter Hello! Thank you for your response! I'm a developer from NoStress Commerce and I work on "Koongo: Sell on Marketplaces" Bigcommerce app. We work with a lot of Bigcommerce stores. Their merchants asked us to add support for googleproductsearch param. At least two merchants currently use it and need it for their business.

Our app allows to import products from Bigcommerce and then export its data along with googleproductsearch data.
This way a merchant can sync their catalogue with Google Merchant Center so that products can be visible in Google search results. This data includes information such as identifiers, product categories, prices, and attributes that help Google to properly display their products and improve their visibility to potential customers.

**Comment by IlyaZha** [comment]
We are utilizing the googleproductsearch endpoint. If possible, we would appreciate support for bulk retrieval of googleproductsearch, as we continuously synchronize these attributes. If this is not feasible, we kindly request that you refrain from removing this endpoint. Thank you.

**Comment by bc-traciporter** [comment]
Thank you for this information @IlyaZha. The team will make a decision and respond back. Please give them some time because some team members are on vacation.

**Comment by bc-traciporter** [comment]
Hello @IlyaZha and @NataliiaNefodova I am just checking on the status of this issue. Has this issue been resolved?

**Comment by IlyaZha** [comment]
If you leave it as it is, that's fine with us. Please don't delete the endpoint googleproductsearch. Thank you

**Comment by bc-traciporter** [comment]
Thank you @IlyaZha. We understand your needs and requirements. Since there is nothing DEVDOCS can do, I will close this issue.
