### ISSUE TITLE
https://developer.bigcommerce.com/docs/rest-authentication/tokens#create-a-token bad example request

### ISSUE THREAD

**Issue by pcfco-kmason** [bigcommerce/docs#377]
### What is the link to the page that needs updating? Provide multiple links if needed.

example has trailing slash in allowed_cors_origins

### What needs to be documented?

remove the trailing slash in the example for allowed_cors_origins:

{
  "allowed_cors_origins": [
    "https://www.yourstorefront.com"
  ],
  "channel_id": 1,
  "expires_at": 1885635176
}
response when using example:
{
    "status": 422,
    "title": "The following fields are invalid: allowed_cors_origins:has_invalid_suffix",
    "type": "https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
    "errors": {
        "allowed_cors_origins:has_invalid_suffix": "A supplied origin has a trailing slash or other special character following the end of the domain. Please remove any trailing characters in supplied origins."
    }
}

### What is currently documented?

{
  "allowed_cors_origins": [
    "https://www.yourstorefront.com/"
  ],
  "channel_id": 1,
  "expires_at": 1885635176
}

**Comment by bc-traciporter** [comment]
Thank you @pcfco-kmason . We are fixing this now in [PR 501](https://github.com/bigcommerce/docs/pull/501).
