### ISSUE TITLE
Upsert a Siteʼs Checkout URL - error when using example

### ISSUE THREAD

**Issue by cmeagher-rwy** [bigcommerce/docs#387]
### What is the link to the page that needs updating? Provide multiple links if needed.

https://developer.bigcommerce.com/docs/rest-management/channels/site-checkout-url#upsert-a-site%CA%BCs-checkout-url

### What needs to be documented?

The `url` in the example is `https://checkout.kittens.mybigcommerce.com`, but if I send a request with my URL including the URL scheme I receive the error `Your checkout and storefront must be within the same main domain like 'main.com' and 'subdomain.main.com'`.

I removed the scheme from the `url` and the request succeeded.

Also I was originally sending the request with a scheme of `http`, because I used the example to [Create a Channel Site](https://developer.bigcommerce.com/docs/rest-management/channels/site#create-a-channel-site) first, but it seems `http` is ignored and `https` is always set - this is for good reason for sure, but it seems including the scheme in both examples is unnecessary.

The examples should be updated to not include the scheme in the `url`.

### What is currently documented?

The example includes the URL scheme in `url`, but this caused an error when sending the request.

**Comment by bc-traciporter** [comment]
Hello @cmeagher-rwy 
Thank you for your feedback. I tested the [Upsert a Site's Checkout](https://developer.bigcommerce.com/docs/rest-management/channels/site-checkout-url#upsert-a-site%CA%BCs-checkout-url) and found the same issue. I updated the example, removing the URL scheme.
For the [Create a Channel Site](https://developer.bigcommerce.com/docs/rest-management/channels/site#create-a-channel-site) endpoint, it would not work without the URL scheme. I simply changed http to https.

You can see these changes in [PR 482](https://github.com/bigcommerce/docs/pull/482).

**Comment by bc-traciporter** [comment]
Hello @cmeagher-rwy Can you try to test the [Upsert a Site's Checkout](https://developer.bigcommerce.com/docs/rest-management/channels/site-checkout-url#upsert-a-site%CA%BCs-checkout-url) endpoint. It should be working with the URL scheme. I tried it today and it worked fine. I am making other changes to this endpoint. You can see these changes in https://github.com/bigcommerce/docs/pull/482.

**Comment by bc-traciporter** [comment]
The changes were merged, so closing the ticket.
