### ISSUE TITLE
/v3/settings/store/locale docs suggest the endpoint is global only

### ISSUE THREAD

**Issue by JamieWT** [bigcommerce/docs#388]
### What is the link to the page that needs updating? Provide multiple links if needed.

https://developer.bigcommerce.com/docs/rest-management/settings/store-locale#get-locale-settings

### What needs to be documented?

The docs don't mention that this endpoint doesn't just return global local settings, it will return channel-specific locale settings too.

### What is currently documented?

The docs say "Returns global locale settings" and there are no notes about the channel_id querystring parameter.  However if you call this endpoint with a channel_id parameter, it will return the channel-specific locale config.

**Comment by bc-andreadao** [comment]
Thanks @JamieWT for bringing this up. The docs will be updated shortly.
