### ISSUE TITLE
Schema anchor links not working

### ISSUE THREAD

**Issue by Dpschu2** [bigcommerce/docs#389]
### What is the link to the page that needs updating? Provide multiple links if needed.

https://developer.bigcommerce.com/docs/storefront/stencil/themes/context/object-reference/schemas#product

### What needs to be documented?

If you open the url anchor link for any schema below forms_contact, it will not work, most likely because that schema has not loaded yet. For example, if you go here: https://developer.bigcommerce.com/docs/storefront/stencil/themes/context/object-reference/schemas#product, it will only go down to forms_contact. This prevents me from sending documentation to other devs.

### What is currently documented?

Currently only scrolls to forms_contact.

**Comment by slsriehl** [comment]
Hey @Dpschu2! Thanks for opening this issue. I've ticketed the work for our DX Platform team to take on when we have capacity.

Internal reference: SELFDEV-763

**Comment by bc-traciporter** [comment]
Hello @Dpschu2 
Unfortunately, this issue has not been worked on due to capacity issues. I will close it due to inactivity. We will fix this issue at a later date.
