### ISSUE TITLE
Feedback for “Live Previewing a Theme”

### ISSUE THREAD

**Issue by RightFootConsulting** [bigcommerce/docs#43]
Your instructions direct us to install latest node LTS version which is currently 20.11.0.  However

$ npm install @bigcommerce/stencil-utils
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bigcommerce/stencil-utils@6.15.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }

up to date, audited 1763 packages in 5s

137 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (21 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by slsriehl** [comment]
Hi @RightFootConsulting! Thanks for raising this issue and building with BigCommerce. We published this change a bit early -- the document has been updated to reflect Node 18 as the recommended version. See #27.

If the docs change doesn't meet your needs, please open a new issue :)
