### ISSUE TITLE
Out of date documentation regarding Stencil CLI --tunnel flag

### ISSUE THREAD

**Issue by 34638a** [bigcommerce/docs#467]
**Describe the bug**
Instructions as of current do not make reference to the new "password" field as required to connect to the tunnel. This was implemented by the tunnel provider to help prevent abuse by malicious parties.

**To Reproduce**
1. run stencil cli with the ```--tunnel``` flag (```stencil start --tunnel```) then connect to the URL indicated to see password page.

**Expected behavior**
This is the expected behaviour as per https://github.com/localtunnel/localtunnel/issues/598

**Expected fix by BC**
Please add content to the description field of the ```--tunnel``` flag to indicate that the password for external connections is your public IP address.

This can be obtained quickly by going to https://ipv4.icanhazip.com/

CURL command: ```curl ipv4.icanhazip.com```
WGET command: ```wget -q -O - ipv4.icanhazip.com```

**Comment by 34638a** [comment]
As a aside, I would be submitting this as a PR but I'm unsure of the expected formatting for the doc's pages. It's on this page in the doc's for future reference https://developer.bigcommerce.com/docs/storefront/stencil/cli/options-and-commands

**Comment by bc-traciporter** [comment]
Hello @34638a ,
I created [PR 474](https://github.com/bigcommerce/docs/pull/474). I added the following sentence:

  The required password for external connections is your public IP address.            |
