### ISSUE TITLE
Github "Bigcommerce" profile, has incorrect repository Pinned for the current Doc's

### ISSUE THREAD

**Issue by 34638a** [bigcommerce/docs#489]
G'day, Me again with another quick one for the Doc's.

This is just a memo noting that the currently pinned documentation repo on the BC profile page is the archived docs.
https://github.com/bigcommerce

Screen shot of the repo in question below:

![image](https://github.com/user-attachments/assets/f8de1501-587b-4ace-9dfc-7074aeb5e569)

Have a good one and thanks for the shot out in the last patch notes.
- JR

**Comment by bc-andreadao** [comment]
Thanks @34638a . I've submitted a ticket to get this fixed.

**Comment by bc-andreadao** [comment]
Closing the ticket since the change is now up.
