### ISSUE TITLE
Feedback for “Regions”

### ISSUE THREAD

**Issue by tvlgiao** [bigcommerce/docs#5]
There is no accessible API for obtaining widget layouts, which makes the backup and restoration of widgets impractical. Please add an API endpoint such as `https://api.bigcommerce.com/stores/{store_hash}/v3/content/layouts` for retrieving widget layouts from a specified page.

**Comment by slsriehl** [comment]
Hi @tvlgiao. I appreciate your patience through the holidays.

We have a new API nearly ready for release that does exactly this: the Page Widgets API. To learn more about the API and release timeline, you can reach out to [community+pagewidgetsapi@bigcommerce.com](mailto:community+pagewidgetsapi@bigcommerce.com). We'll have docs available in the [Widgets section (developer.bigcommerce.com)](https://developer.bigcommerce.com/docs/storefront/widgets) of the documentation as soon as the feature is officially released.
