### ISSUE TITLE
Feedback for “Manage Webhooks Single”

### ISSUE THREAD

**Issue by cjbarth** [bigcommerce/docs#506]
When calling Update a webhook, and also Create a webhook, I note that `events_order_history` isn't obeyed. No matter how many times I send `true`, I always get `false` in response.

For example, I send (extra data because of the problem reported in #505):

```json
{
  "scope": "store/order/created",
  "events_history_enabled": true
}
```

I get the following in response (redacted):

```json
{
    "data": {
        "id": ...,
        "client_id": "...",
        "store_hash": "...",
        "scope": "store/order/created",
        "destination": "https://...",
        "headers": null,
        "is_active": true,
        "created_at": 1725633095,
        "updated_at": 1725633095,
        "events_history_enabled": false
    },
    "meta": {}
}
```

There is nothing in the documentation outlining why sending `true` for `events_hisotyr_enabled` would cause it to return `false` for that property.

**Comment by bc-traciporter** [comment]
This field was removed in [PR 513](https://github.com/bigcommerce/docs/pull/513).
