### ISSUE TITLE
Feedback for “Products”

### ISSUE THREAD

**Issue by fncscafred** [bigcommerce/docs#563]
I was fetching data from `https://api.bigcommerce.com/stores/{store_hash}/v3/catalog/products/{product_id}` with the parameters `"include_fields": 'reviews_count,reviews_rating_sum'`. On the BigCommerce live site, the `reviews_count` and `reviews_rating_sum` are showing as 0, but the API is returning non-zero values. I’ve verified that the product IDs match, so I'm not sure why the live site is displaying 0.

**Comment by bc-traciporter** [comment]
Hello @fncscafred Thank you for your feedback. I have taken your issue to our development team and we will get back to you.

**Comment by bc-traciporter** [comment]
Hello @fncscafred 
When a merchant creates a review for a purchased product, they select a rating from the drop-down menu (from 1 to 5 stars). When this review is sent and approved => `reviews_count` will increase by +1, and `reviews_rating_sum` will be increased by the value of the rating for the product.

**Comment by fncscafred** [comment]
Hi @bc-traciporter. I understand that. However, I noticed something unusual. When I fetch data using the API and specific parameters, I'm still getting a value for a product that currently has no visible reviews. This leads me to believe that the API might be returning data for reviews that have been deleted or hidden, as the count doesn't seem to reflect the current number of active reviews.

**Comment by bc-traciporter** [comment]
Hi @fncscafred Thank you for this information. The team will investigate and fix this behavior.

**Comment by bc-traciporter** [comment]
Closing this ticket due to inactivity. There is a ticket for the catalog team to perform this work. I can reopen the issue or communicate when the ticket is resolved.
