### ISSUE TITLE
Feedback for “Filtering” - Need to List Max limit Value

### ISSUE THREAD

**Issue by sshaw** [bigcommerce/docs#567]
I think the max is `250` but docs should state this.

**Comment by sshaw** [comment]
Oopsy, I see it's at the top of the page and not with the query parameter. I'd add it [here](https://developer.bigcommerce.com/docs/start/about/common-query-params#pagination-and-limit) for good measure

**Comment by bc-traciporter** [comment]
Thank you @sshaw , I created [PR 572 ](https://github.com/bigcommerce/docs/pull/572) to add the limit.
