### ISSUE TITLE
Feedback for “Customers” – Where's The Error Response Bodies? 

### ISSUE THREAD

**Issue by sshaw** [bigcommerce/docs#581]
https://developer.bigcommerce.com/docs/rest-management/customers

Response section has a `200` tab but nothing describing what an error response looks like.  

Nothing here either: https://developer.bigcommerce.com/docs/start/about/status-codes

**Comment by bc-traciporter** [comment]
Hi @sshaw thank you for your feedback. We can add error responses to this endpoint. 
The link you added above contains descriptions for 200, 300, 400 and 500 status codes.

**Comment by sshaw** [comment]
> The link you added above contains descriptions for 200, 300, 400 and 500 status codes.

I meant that this link does not describe error response bodies

**Comment by bc-traciporter** [comment]
Hi @sshaw 
There are descriptions for all the [400 codes](https://developer.bigcommerce.com/docs/start/about/status-codes#4xx-client-error), which are error codes. Can you be more specific regarding what you would like to see?

I did add 422 error codes to the Customer reference documentation.
https://developer.bigcommerce.com/docs/rest-management/customers#get-all-customers
https://developer.bigcommerce.com/docs/rest-management/customers#delete-customers

**Comment by bc-traciporter** [comment]
Closing this issue, if you have additional feedback I can reopen the issue.

**Comment by sshaw** [comment]
> There are descriptions for all the [400 codes](https://developer.bigcommerce.com/docs/start/about/status-codes#4xx-client-error), which are error codes. Can you be more specific regarding what you would like to see?

Response body for errors responses. Status codes are shown but response bodies are not. 
Some customer endpoint docs show response bodies for errors but others do not. In the case of customers v3 no error response bodies are shown but they can be returned. For example: 

```
 /stores/ID/v3/customers/addresses?x=1
```

Will result in: 
```ruby
{"status"=>422,
 "title"=>"The filter(s): x are not valid filter parameter(s).",
 "type"=>
  "https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
 "errors"=>{}}
```

This is not described anywhere outside of "we can return a 422".

**Comment by bc-traciporter** [comment]
Hello @sshaw I am sorry for the late response. Ideally, the relevant error response bodies should appear in the API reference file. We will update the reference files if these response bodies are missing. I hope this helps.
