### ISSUE TITLE
Feedback for “Subscribers”

### ISSUE THREAD

**Issue by sshaw** [bigcommerce/docs#583]
https://developer.bigcommerce.com/docs/rest-management/subscribers#get-subscribers

The params are `XXX:in` params. For example it says: 

> id in query 

But this is. `id:in` not `id`. This looks to apply to all the "in" parameters on that page. You can see [on the customer's page](https://developer.bigcommerce.com/docs/rest-management/customers) it's described correctly. 

Also `date_modified`, is it `date_modified` or `date_modified:min`? The example given is for `last_imported:min` which, given the docs, is not a valid param.

**Comment by bc-traciporter** [comment]
Hello @sshaw 
I tested the parameters. Here is the `id` parameter. 
![Screenshot 2024-10-16 at 9 09 01 AM](https://github.com/user-attachments/assets/dec8ccdb-b4ac-47e7-ba5f-70a15b2fe79d)
And here is the `date_modified` parameter.
![Screenshot 2024-10-16 at 9 10 50 AM](https://github.com/user-attachments/assets/cc043327-c222-4f2d-85a1-112f391cc9fb)
Can you please clarify the issue with these?

**Comment by sshaw** [comment]
Then it appears 2 forms are supported: `id`, `id:in`, `date_modified` and `date_modified:min`. Is it intended that the 2nd forms are supported and just undocumented?

**Comment by bc-traciporter** [comment]
Thank you @sshaw I will look into this issue.

**Comment by bc-traciporter** [comment]
Hello @sshaw thank you for bringing these parameters to our attention. I am in the process of adding additional query parameters to the Get Subscribers endpoint. I will let you know when the documentation is updated.

**Comment by bc-traciporter** [comment]
The [Get Subscribers](https://developer.bigcommerce.com/docs/rest-management/subscribers#get-subscribers) endpoint has been updated.
