### ISSUE TITLE
Feedback for “Categories”

### ISSUE THREAD

**Issue by atensoftware** [bigcommerce/docs#59]
Example JSON for POST /catalog/trees/categories currently is missing category_id in the sample response.
Instead, it should include category_id just above "parent_id"

CURRENTLY:
```
{
  "data": [
    {
      "parent_id": 2,
      "name": "Bath",
```

INSTEAD:
```
{
  "data": [
    {
      "category_id": 6,
      "parent_id": 2,
      "name": "Bath",
```

**Comment by slsriehl** [comment]
This should be resolved. Please open a new issue or pull request for any further feedback. Thanks for developing with BigCommerce!
