### ISSUE TITLE
Documented response schema is incorrect for GET https://api-b2b.bigcommerce.com/api/v3/io/payments

### ISSUE THREAD

**Issue by bbogovich-vs** [bigcommerce/docs#602]
**Describe the bug**
The "code" field of the response model object for the /payments endpoint is actually named "paymentCode".

The documentation currently shows the response schema for GET /payments to be:
`{
  "code": 200,
  "meta": {
    "message": "SUCCESS"
  },
  "data": [
    {
      "id": 1,
      "code": "cheque",
      "paymentTitle": "Check"
    },
    {
      "id": 2,
      "code": "braintree",
      "paymentTitle": "Braintree"
    },
    {
      "id": 3,
      "code": "authorizenet",
      "paymentTitle": "Authorize.net"
    }
  ]
}`

The actual response schema is like so:
`{
  "code": 200,
  "data": [
    {
      "id": 1,
      "paymentCode": "bigpaypay",
      "paymentTitle": "Test payment provider"
    },
    {
      "id": 2,
      "paymentCode": "bigcommerce_store_credit",
      "paymentTitle": "Store Credit"
    },
    {
      "id": 3,
      "paymentCode": "bigcommerce_gift_certificate",
      "paymentTitle": "Gift Certificate"
    },
    {
      "id": 4,
      "paymentCode": "bigcommerce_manual_payment",
      "paymentTitle": "Manual Payment"
    }
  ],
  "meta": {
    "message": "SUCCESS"
  }
}`

The issue is that the specs for the /payments endpoint and the /companies/{companyId}/payments endpoint in [https://github.com/bigcommerce/docs/blob/main/docs/b2b-edition/specs/api-v3/payment/payment.yaml](https://github.com/bigcommerce/docs/blob/main/docs/b2b-edition/specs/api-v3/payment/payment.yaml) both reference [https://github.com/bigcommerce/docs/blob/main/docs/b2b-edition/models/payment/payment.yaml](https://github.com/bigcommerce/docs/blob/main/docs/b2b-edition/models/payment/payment.yaml) as their response model object, but the two endpoints do not actually match.  /companies/{companyId}/payments uses "code" for the payment method code, as shown in the docs, but /payments uses "paymentCode" instead.  This makes this more than just a quick edit to the docs, hence the bug report.

**To Reproduce**
Make a GET request to https://api-b2b.bigcommerce.com/api/v3/io/payments.  You will see that the response schema does not match the documentation.

**Expected behavior**
The docs should reflect the actual response schema for the B2B /payments endpoint.

![payments-incorrect-schema](https://github.com/user-attachments/assets/da62ffbd-516d-45e4-aabf-1a8843a2681e)

**Comment by bc-traciporter** [comment]
Thank you @bbogovich-vs for letting us know of this issue. We are in the process of fixing it.

**Comment by bc-traciporter** [comment]
This issue has been resolved in [PR 618](https://github.com/bigcommerce/docs/pull/618). The documentation will be updated shortly.
