### ISSUE TITLE
multiConcat Handlebar Helper is not documented

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/docs#628]
We really appreciate the help making our docs better. Every issue helps!

**Describe the bug**
`multiConcat` Handlebar Helper is not documented.
[Handlebar code](https://github.com/bigcommerce/paper-handlebars/blob/master/helpers/multiConcat.js)

**To Reproduce**
N/A

Please link to a repo that can be used to reproduce this issue, if possible. It'll help fix the bug faster.

**Expected behavior**
`multiConcat` is documented

**Screenshots**
N/A

**Additional context**
PR Incoming 📨

**Comment by bc-traciporter** [comment]
Thank you @AndrewBarber These changes have been merged in [PR 629](https://github.com/bigcommerce/docs/pull/629).
